### ISSUE TITLE
怎样运行视频

### ISSUE THREAD

**Issue by GaoTianWL** [Srameo/DNF#12]
您好，您的代码效果非常理想在单张图片上，我想在视频上进行处理需要怎么操作呢？非常感谢！

**Comment by Srameo** [comment]
不好意思之前有点事在忙，能问下你的视频是什么格式的呢？可以转换成多帧RAW图像流吗？

**Comment by GaoTianWL** [comment]
您好，很抱歉打扰您。视频功能大概可以实现。视频是MP4的，我试着转成单帧图像的无法运行，但是我用您的数据集里面图片拼起来测试视频功能是完全可以的。




田高
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Srameo/DNF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月31日(星期四) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Srameo/DNF] 怎样运行视频 (Issue #12)





 
不好意思之前有点事在忙，能问下你的视频是什么格式的呢？可以转换成多帧RAW图像流吗？

**Comment by Srameo** [comment]
您好！

由于DNF是面向图像RAW数据增强的神经网络，因此对于RGB颜色空间的mp4文件暂不具有增强能力。
如果您可以收集到RAW视频（或图像连拍序列），您可以尝试使用我们所提供的demo脚本进行多帧图像增强。

免责声明：由于DNF是图像处理算法，因此直接用于处理图像可能会出现帧间闪烁的现象

**Comment by GaoTianWL** [comment]
非常感谢您的回复！




田高
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Srameo/DNF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Srameo/DNF] 怎样运行视频 (Issue #12)





 
您好！
 
由于DNF是面向图像RAW数据增强的神经网络，因此对于RGB颜色空间的mp4文件暂不具有增强能力。
 如果您可以收集到RAW视频（或图像连拍序列），您可以尝试使用我们所提供的demo脚本进行多帧图像增强。
 
免责声明：由于DNF是图像处理算法，因此直接用于处理图像可能会出现帧间闪烁的现象
