### ISSUE TITLE
why can't find the result

### ISSUE THREAD

**Issue by Catherineasdzz** [Srameo/DNF#5]
When I run `bash demos/images_process.sh` successfully, I can only find .log and .yaml in `runs/CVPR_DEMO/image_demo`, and could not find results

**Comment by Srameo** [comment]
Hello! Could you please provide the runtime commands, the last 30 lines of the log file, and your specific runtime environment?

**Comment by Catherineasdzz** [comment]
Hello, thank you for your reply! I am using a GPU on an online server, and I have set up the environment according to the instructions you provided.
And this is the command I use:
![image](https://github.com/Srameo/DNF/assets/118364078/5677e12e-b7e2-4f69-b949-63f4dfb57dac)
And the log is like that:
![image](https://github.com/Srameo/DNF/assets/118364078/6e0cf5c8-6654-4d91-9e11-49c5263ed0e7)
![image](https://github.com/Srameo/DNF/assets/118364078/17673156-3978-4ac6-9199-1f94897f5070)

**Comment by Srameo** [comment]
It appears that our script did not find any images to process.

The `-d` parameter in the program only supports passing a **folder** path, not a file path. Additionally, the script currently only supports Sony's ".ARW" data format and the ".npy" format. If you have downloaded our Demo data, you can try passing the `short_pack` folder path and add the `-a` parameter at the end of the command (to indicate that the data format is ".npy"). You can find more details in readme.

The commands should be like:
```bash
bash demos/images_process.sh -p pretrained/model_best_sid_sony.pth -d /root/autodl-tmp/Campus/short_pack -r 100 -a 
```

**Comment by Catherineasdzz** [comment]
The problem has been solved! Thank you very much! And if I want to use my own images, do I still need to convert them to the npy format first?

**Comment by Srameo** [comment]
If your images are in Sony ARW format, there is no need to convert the data to the .npy format. However, for other data formats, you will need to convert the RAW data to the "RGBG 4-channel" format and save it as .npy files. You can refer to the specific conversion code in `scripts/preprocess/preprocess_sid.py` for the conversion process.

**Comment by Catherineasdzz** [comment]
Got it! Thank you very much!
