### ISSUE TITLE
Sony_new_test_list.txt

### ISSUE THREAD

**Issue by Qirui-Y** [Srameo/DNF#6]
Hello, I enjoyed reading your excellent highlight paper. Can the author provide the corresponding "Sony_new_test_list.txt" or a method to discard the unaligned test data for SID data?

**Comment by Srameo** [comment]
Hello, this is indeed our negligence as we did not mention the specific configuration in the our readme. 

The Sony_new_test_list.txt has now been uploaded to [Google Drive](https://drive.google.com/file/d/1nrtcZc39W4b_SJrCoMgfaO14LGem4s6O/view) and will be promptly updated in the readme as well. 

We will close the issue after the update. Thank you!

**Comment by Qirui-Y** [comment]
邮件可能无法及时回复，如有查收会尽快回复您。

**Comment by Srameo** [comment]
We have updated the information regarding Sony_new_test_list.txt in commit https://github.com/Srameo/DNF/commit/6a5c0f1859c9a092b9d7a8f10c3c028a809bcd60. This issue will be closed.

**Comment by Qirui-Y** [comment]
邮件可能无法及时回复，如有查收会尽快回复您。
