### ISSUE TITLE
MCR txt files

### ISSUE THREAD

**Issue by ekeronur** [Srameo/DNF#8]
Hi, thanks for your outstanding work. I cannot find the MCR txt files in the repository. Could you please provide the corresponding "MCR_test_list.txt" and "MCR_train_list.txt" files to train and evaluate on the MCR dataset?

**Comment by Srameo** [comment]
We are sorry for our oversight.

We have update all the txt files in our readme.md. You can also found them in [Google Drive](https://drive.google.com/drive/folders/1DIuBcbq0wjbzmmSp0XSp7vrnW-jiKLFD).

Besides, [links](https://drive.google.com/drive/folders/1auXCb-k6jPqwoGPGrb0QcA4CNisD99jF) to all files are also already updated in the readme.
