### ISSUE TITLE
how to calculate lpips

### ISSUE THREAD

**Issue by junnjxx** [Srameo/DNF#9]
Hello,

I've been attempting to understand how the lpips calculation is performed, but I have been unable to locate the corresponding code within your repository. Would you kindly provide me with the location of the relevant code? While this may be a straightforward matter for you, it would greatly help in resolving my current predicament. Thank you very much for your assistance!

**Comment by Srameo** [comment]
Thank you for your attention to DNF! 

Our metrics on lpips is calculated using the pyiqa package and the generated images by our DNF (saved on disks). 
You can refer to the official repo of [pyiqa](https://github.com/chaofengc/IQA-PyTorch) for more details.
